# Generated by Django 4.1.5 on 2023-04-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='reports/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type_tag', models.CharField(choices=[('PL', 'Plastic'), ('FU', 'Furniture'), ('ME', 'Metal'), ('FO', 'Food'), ('DA', 'Dangerous'), ('OT', 'Other'), ('NO', 'None')], default='NO', max_length=2)),
                ('quantity_tag', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('LRG', 'Large'), ('NON', 'None')], default='NON', max_length=3)),
                ('extra_description', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
