# Generated by Django 4.1.5 on 2023-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trashporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type_tag',
            field=models.CharField(choices=[('PL', 'Plastic'), ('FU', 'Furniture'), ('ME', 'Metal'), ('FO', 'Food'), ('DA', 'Dangerous'), ('OT', 'Other'), ('GL', 'Glass'), ('NO', 'None')], default='NO', max_length=2),
        ),
    ]
