# Generated by Django 4.1.5 on 2023-04-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trashporter', '0002_alter_report_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='extra_description',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='quantity_tag',
            field=models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('LRG', 'Large')], default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='report',
            name='type_tag',
            field=models.CharField(choices=[('PL', 'Plastic'), ('FU', 'Furniture'), ('ME', 'Metal'), ('FO', 'Food'), ('DA', 'Dangerous'), ('OT', 'Other')], default=None, max_length=2),
        ),
    ]
