# Generated by Django 4.1.5 on 2023-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trashporter', '0002_alter_report_type_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='quantity_tag',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Large', 'Large'), ('None', 'None')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='type_tag',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Furniture', 'Furniture'), ('Metal', 'Metal'), ('Food', 'Food'), ('Dangerous', 'Dangerous'), ('Other', 'Other'), ('Glass', 'Glass'), ('None', 'None')], default='None', max_length=15),
        ),
    ]
